[package]
name = "test_project"
version = "0.1.0"
authors = ["leo2436 <chenll1996@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
